version: '3'

services:
  https-server:
    build:
      context: ./https-server/
      args:
        http_proxy:
        https_proxy:
    volumes:
      - root_key:/root/.root-key
      - ./.generated:/root/.generated
      - ./.provided-root-ca:/root/.provided-root-ca
    env_file: ./.env
    ports:
      - "${FORWARDING_SERVER_BIND_IP:-127.9.9.9}:${TARGET_PORT:-443}:443"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"

  http-proxy-server:
    build:
      context: ./http-proxy-server/
      args:
        http_proxy:
        https_proxy:
    depends_on:
      - https-server
    environment:
      FORWARDING_CONTAINER: "https-server"
    env_file: ./.env
    ports:
      - "${HTTP_PROXY_SERVER_BIND_IP_PORT:-127.0.0.1:3128}:3128"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"


volumes:
  root_key:
