version: '3'

services:
  root-ca:
    build:
      context: ./root-ca/
      args:
        http_proxy:
        https_proxy:
    volumes:
      - ./.generated:/root/.generated
    environment:
      ROOT_CERT_COMMON_NAME:
